"""added nuotrauka to vartotojas

Revision ID: 1b1018dc245a
Revises: fd59fdd8bd4c
Create Date: 2022-05-04 20:28:38.042415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1018dc245a'
down_revision = 'fd59fdd8bd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vartotojas_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vartotojas', ['vartotojas_id'], ['id'])

    with op.batch_alter_table('vartotojas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nuotrauka', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojas', schema=None) as batch_op:
        batch_op.drop_column('nuotrauka')

    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vartotojas_id')
        batch_op.drop_column('Data')

    # ### end Alembic commands ###
