"""added nuotrauka to vartotojas

Revision ID: 843ffdd28070
Revises: aa1ac529dec4
Create Date: 2022-05-04 20:58:57.906904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843ffdd28070'
down_revision = 'aa1ac529dec4'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Budget')
    with op.batch_alter_table('Budget', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('Data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vartotojas_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Budget_vartotojas_id_vartotojas'), 'vartotojas', ['vartotojas_id'], ['id'])

    with op.batch_alter_table('vartotojas', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('nuotrauka', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_vartotojas_El. pašto adresas'), ['El. pašto adresas'])
        batch_op.create_unique_constraint(batch_op.f('uq_vartotojas_Slaptažodis'), ['Slaptažodis'])
        batch_op.create_unique_constraint(batch_op.f('uq_vartotojas_Vardas'), ['Vardas'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vartotojas_Vardas'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vartotojas_Slaptažodis'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vartotojas_El. pašto adresas'), type_='unique')
        batch_op.drop_column('nuotrauka')

    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Budget_vartotojas_id_vartotojas'), type_='foreignkey')
        batch_op.drop_column('vartotojas_id')
        batch_op.drop_column('Data')

    op.create_table('_alembic_tmp_Budget',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry', sa.VARCHAR(length=80), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(length=80), nullable=True),
    sa.Column('extra_information', sa.VARCHAR(length=200), nullable=True),
    sa.Column('payment_option', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bought_goods_or_services', sa.VARCHAR(length=200), nullable=True),
    sa.Column('Data', sa.DATETIME(), nullable=True),
    sa.Column('vartotojas_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
