"""added nuotrauka to vartotojas

Revision ID: aa1ac529dec4
Revises: 1b1018dc245a
Create Date: 2022-05-04 20:50:04.252003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1ac529dec4'
down_revision = '1b1018dc245a'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Budget', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('Data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vartotojas_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Budget_vartotojas_id_vartotojas'), 'vartotojas', ['vartotojas_id'], ['id'])

    with op.batch_alter_table('vartotojas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nuotrauka', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_vartotojas_El. pašto adresas'), ['El. pašto adresas'])
        batch_op.create_unique_constraint(batch_op.f('uq_vartotojas_Slaptažodis'), ['Slaptažodis'])
        batch_op.create_unique_constraint(batch_op.f('uq_vartotojas_Vardas'), ['Vardas'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vartotojas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vartotojas_Vardas'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vartotojas_Slaptažodis'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vartotojas_El. pašto adresas'), type_='unique')
        batch_op.drop_column('nuotrauka')

    with op.batch_alter_table('Budget', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Budget_vartotojas_id_vartotojas'), type_='foreignkey')
        batch_op.drop_column('vartotojas_id')
        batch_op.drop_column('Data')

    # ### end Alembic commands ###
